package be.rlab.afip.person.model

import org.joda.time.DateTime

data class PersonA4(
    val cuit: Long?,
    val personType: PersonType?,
    val taxIdType: TaxIdType?,
    val taxIdStatus: TaxIdStatus?,
    val firstName: String?,
    val lastName: String?,
    val companyName: String?,
    val documentType: String?,
    val documentNumber: String?,
    val closeMonth: Int?,
    val registrationDate: DateTime?,
    val socialContractDate: DateTime?,
    val birthDate: DateTime?,
    val retirementDate: DateTime?,
    val deathDate: DateTime?,
    val gender: Gender?,
    val legalNature: String?,
    val residenceType: String?,
    val addresses: List<Address>,
    val taxes: List<Tax>,
    val categories: List<Category>,
    val phones: List<Phone>,
    val emails: List<Email>,
    val activities: List<Activity>,
    val legalFrameworks: List<LegalFramework>,
    val relationships: List<Relationship>,
    val dependency: Dependency?,
    val registryNumber: String?,
    val registryOrganization: String?,
    val registryTown: String?,
    val registryProvince: String?,
    val migrationExpirationDate: DateTime?,
    val numberOfPartners: Int?,
    val sourceRegistry: String?,
    val sourceRegistryType: String?,
    val retirementLaw: Int?,
)
